<?php

return [
    'default' => env('SITE_DEFAULT_CONNECTION', 'mysql'),

    'sites' => [

        'himrishtey.com' => [
            'search_state' => 'Himachal Pradesh',
            'hosts' => ['himrishtey.ddev.site'],
            'name' => env('SITE1_NAME', 'Himrishtey'),
            'display_name' => env('SITE1_DISPLAY_NAME', 'HimRishtey'),
            'connection' => env('SITE1_DB_CONNECTION', 'site1'),
            'app_url' => env('SITE1_APP_URL', 'https://himrishtey.com'),
            'session_cookie' => env('SITE1_SESSION_COOKIE', 'himrishtey_session'),
            'logo' => env('SITE1_LOGO', 'assets/images/himrishtey-logo.png'),
            'tagline' => env('SITE1_TAGLINE', 'Trusted matching for Himachali families.'),
            'footer_text' => env('SITE1_FOOTER_TEXT', 'Connecting hearts across Himachal Pradesh & beyond.'),
            'hero_badge' => env('SITE1_HERO_BADGE', "Himachal Pradesh's Most Trusted Matrimony"),
            'hero_title' => env('SITE1_HERO_TITLE', 'We Connect Hearts, Not Just Relationships'),
            'hero_title_secondary' => env('SITE1_HERO_TITLE_SECONDARY', 'Find your forever from the hills.'),
            'hero_subtitle' => env('SITE1_HERO_SUBTITLE', 'Thousands of happy Himachali families found their perfect match through HimRishtey.'),
            'hero_background' => env('SITE1_HERO_BACKGROUND', 'assets/images/hero-himrishtey.jpg'),
            'hero_cta_primary' => env('SITE1_HERO_CTA_PRIMARY', 'Create Your Profile'),
            'hero_cta_secondary' => env('SITE1_HERO_CTA_SECONDARY', 'Browse Profiles'),
            'show_hero_stats' => env('SITE1_SHOW_HERO_STATS', true),
            'why_title' => env('SITE1_WHY_TITLE', 'Everything You Need on One Platform'),
            'why_text' => env('SITE1_WHY_TEXT', 'HimRishtey brings profile discovery, advanced search, verification, shortlist features and family-friendly support together in one place.'),
            'community_title' => env('SITE1_COMMUNITY_TITLE', 'Matches for Every Himachali Family'),
            'community_subtitle' => env('SITE1_COMMUNITY_SUBTITLE', 'HimRishtey offers profiles across castes, communities, professions, education levels and family backgrounds.'),
            'primary_color' => env('SITE1_PRIMARY_COLOR', '#b92c3d'),
            'secondary_color' => env('SITE1_SECONDARY_COLOR', '#2f2d5c'),
            'accent_color' => env('SITE1_ACCENT_COLOR', '#f4c86c'),
            'support_email' => env('SITE1_SUPPORT_EMAIL', 'himrishtey@gmail.com'),
            'support_phone' => env('SITE1_SUPPORT_PHONE', '+91 9459170004'),
            'support_address' => env('SITE1_SUPPORT_ADDRESS', '1st Floor, Manali, Mandi - Pathankot Road, Opp. Palam Hardware Kalu Ki Hatti, Bag Uparla, Palampur, Himachal Pradesh 176102'),
            'social' => [
                'facebook' => env('SITE1_SOCIAL_FACEBOOK', 'https://www.facebook.com/himrishtey'),
                'x' => env('SITE1_SOCIAL_X', 'https://x.com/himrishte'),
                'instagram' => env('SITE1_SOCIAL_INSTAGRAM', 'https://www.instagram.com/himrishtey/'),
                'youtube' => env('SITE1_SOCIAL_YOUTUBE', 'https://www.youtube.com/channel/UCwIe3GhJL-_c0bQ80eFv6RQ'),
            ],

            'instagram' => [
                'enabled' => true,
                'username' => 'himrishtey',
                'url' => 'https://www.instagram.com/himrishtey/',
                'user_id' => env('HIMRISHTEY_INSTAGRAM_USER_ID'),
                'access_token' => env('HIMRISHTEY_INSTAGRAM_ACCESS_TOKEN'),
            ],
            'android_app_url' => env('SITE1_ANDROID_APP_URL', 'https://play.google.com/store/apps/details?id=com.app.himrishtey&hl=en_IN'),
            'ios_app_url' => env('SITE1_IOS_APP_URL', 'https://apps.apple.com/in/search?term=HimRishtey'),
        ],
        'dogririshtey.com' => [
            'search_state' => 'Jammu and Kashmir',
            'hosts' => ['dogririshtey.ddev.site'],
            'name' => env('SITE2_NAME', 'Dogri Rishtey'),
            'display_name' => env('SITE2_DISPLAY_NAME', 'Dogri Rishtey'),
            'connection' => env('SITE2_DB_CONNECTION', 'site2'),
            'app_url' => env('SITE2_APP_URL', 'https://dogririshtey.com'),
            'session_cookie' => env('SITE2_SESSION_COOKIE', 'dogririshtey_session'),
            'logo' => env('SITE2_LOGO', 'assets/images/dogri-rishtey-logo.png'),
            'tagline' => env('SITE2_TAGLINE', 'Rooted in tradition, built for modern matches.'),
            'footer_text' => env('SITE2_FOOTER_TEXT', 'Finding meaningful matches for Dogri families.'),
            'hero_badge' => env('SITE2_HERO_BADGE', "Dogri culture. Trusted relationships."),
            'hero_title' => env('SITE2_HERO_TITLE', 'Celebrate tradition with a modern match'),
            'hero_title_secondary' => env('SITE2_HERO_TITLE_SECONDARY', 'Made for Dogri families.'),
            'hero_subtitle' => env('SITE2_HERO_SUBTITLE', 'Dogri Rishtey helps families discover thoughtful, value-driven matches rooted in culture and compatibility.'),
            'hero_background' => env('SITE2_HERO_BACKGROUND', 'assets/images/hero-dogri.jpg'),
            'hero_cta_primary' => env('SITE2_HERO_CTA_PRIMARY', 'Create Your Profile'),
            'hero_cta_secondary' => env('SITE2_HERO_CTA_SECONDARY', 'Browse Profiles'),
            'show_hero_stats' => env('SITE2_SHOW_HERO_STATS', true),
            'why_title' => env('SITE2_WHY_TITLE', 'A trusted platform for Dogri families'),
            'why_text' => env('SITE2_WHY_TEXT', 'From community-based matching to personalized preferences, Dogri Rishtey supports thoughtful connections for a new generation.'),
            'community_title' => env('SITE2_COMMUNITY_TITLE', 'Connections across Dogri roots and modern life'),
            'community_subtitle' => env('SITE2_COMMUNITY_SUBTITLE', 'Meet people aligned by values, family background, lifestyle and future goals across the Dogri community.'),
            'primary_color' => env('SITE2_PRIMARY_COLOR', '#4a5d23'),
            'secondary_color' => env('SITE2_SECONDARY_COLOR', '#1b1c1d'),
            'accent_color' => env('SITE2_ACCENT_COLOR', '#d6b36a'),
            'support_email' => env('SITE2_SUPPORT_EMAIL', 'info@dogririshtey.com'),
            'support_phone' => env('SITE2_SUPPORT_PHONE'),
            'support_address' => env('SITE2_SUPPORT_ADDRESS'),
            'social' => [
                'facebook' => env('SITE2_SOCIAL_FACEBOOK'),
                'x' => env('SITE2_SOCIAL_X'),
                'instagram' => env('SITE2_SOCIAL_INSTAGRAM'),
                'youtube' => env('SITE2_SOCIAL_YOUTUBE'),
            ],
            'android_app_url' => env('SITE2_ANDROID_APP_URL'),
            'ios_app_url' => env('SITE2_IOS_APP_URL'),
        ],
        'gallpakki.com' => [
            'search_state' => 'Punjab',
            'hosts' => ['gallpakki.ddev.site'],
            'name' => env('SITE3_NAME', 'Gallpakki'),
            'display_name' => env('SITE3_DISPLAY_NAME', 'Gallpakki'),
            'connection' => env('SITE3_DB_CONNECTION', 'site3'),
            'app_url' => env('SITE3_APP_URL', 'https://gallpakki.com'),
            'session_cookie' => env('SITE3_SESSION_COOKIE', 'gallpakki_session'),
            'logo' => env('SITE3_LOGO', 'assets/images/gallpakki-logo.png'),
            'tagline' => env('SITE3_TAGLINE', 'Matrimony for families and communities that value culture.'),
            'footer_text' => env('SITE3_FOOTER_TEXT', 'Trusted relationships for the Gallpakki community.'),
            'hero_badge' => env('SITE3_HERO_BADGE', "Community-first matchmaking"),
            'hero_title' => env('SITE3_HERO_TITLE', 'Where values, culture, and love meet'),
            'hero_title_secondary' => env('SITE3_HERO_TITLE_SECONDARY', 'For Gallpakki families.'),
            'hero_subtitle' => env('SITE3_HERO_SUBTITLE', 'Gallpakki brings families together through thoughtful profiles, genuine compatibility, and respectful introductions.'),
            'hero_background' => env('SITE3_HERO_BACKGROUND', 'assets/images/hero-gallpakki.jpg'),
            'hero_cta_primary' => env('SITE3_HERO_CTA_PRIMARY', 'Create Your Profile'),
            'hero_cta_secondary' => env('SITE3_HERO_CTA_SECONDARY', 'Browse Profiles'),
            'show_hero_stats' => env('SITE3_SHOW_HERO_STATS', true),
            'why_title' => env('SITE3_WHY_TITLE', 'A respectful start to a lifelong journey'),
            'why_text' => env('SITE3_WHY_TEXT', 'Connect with families who value trust, compatibility and meaningful relationships built around strong community roots.'),
            'community_title' => env('SITE3_COMMUNITY_TITLE', 'Profiles shaped by culture and compatibility'),
            'community_subtitle' => env('SITE3_COMMUNITY_SUBTITLE', 'Explore matches that honor traditions while supporting modern family preferences and long-term goals.'),
            'primary_color' => env('SITE3_PRIMARY_COLOR', '#8c4a2f'),
            'secondary_color' => env('SITE3_SECONDARY_COLOR', '#2c2a27'),
            'accent_color' => env('SITE3_ACCENT_COLOR', '#d8b35a'),
            'support_email' => env('SITE3_SUPPORT_EMAIL', 'info@gallpakki.com'),
            'support_phone' => env('SITE3_SUPPORT_PHONE'),
            'support_address' => env('SITE3_SUPPORT_ADDRESS'),
            'social' => [
                'facebook' => env('SITE3_SOCIAL_FACEBOOK'),
                'x' => env('SITE3_SOCIAL_X'),
                'instagram' => env('SITE3_SOCIAL_INSTAGRAM'),
                'youtube' => env('SITE3_SOCIAL_YOUTUBE'),
            ],
            'android_app_url' => env('SITE3_ANDROID_APP_URL'),
            'ios_app_url' => env('SITE3_IOS_APP_URL'),
        ],
        'devbhoomirishte.com' => [
            'search_state' => 'Uttarakhand',
            'hosts' => ['devbhoomi.ddev.site', 'devbhoomirishtey.com'],
            'name' => env('SITE4_NAME', 'Dev Bhoomi Rishtey'),
            'display_name' => env('SITE4_DISPLAY_NAME', 'Dev Bhoomi Rishtey'),
            'connection' => env('SITE4_DB_CONNECTION', 'site4'),
            'app_url' => env('SITE4_APP_URL', 'https://devbhoomirishte.com'),
            'session_cookie' => env('SITE4_SESSION_COOKIE', 'devbhoomirishtey_session'),
            'logo' => env('SITE4_LOGO', 'assets/images/logo/devbhoomirishtey-logo.png'),
            'tagline' => env('SITE4_TAGLINE', 'Connecting the Dev Bhoomi community with trusted matches.'),
            'footer_text' => env('SITE4_FOOTER_TEXT', 'A modern matrimony platform for Dev Bhoomi families.'),
            'hero_badge' => env('SITE4_HERO_BADGE', "Sacred traditions. Modern connections."),
            'hero_title' => env('SITE4_HERO_TITLE', 'Bring together faith, family, and future'),
            'hero_title_secondary' => env('SITE4_HERO_TITLE_SECONDARY', 'For the Dev Bhoomi community.'),
            'hero_subtitle' => env('SITE4_HERO_SUBTITLE', 'Dev Bhoomi Rishtey helps families connect through shared values, compatibility and respectful matchmaking.'),
            'hero_background' => env('SITE4_HERO_BACKGROUND', 'assets/images/home/devbhoomi-hero.png'),
            'hero_cta_primary' => env('SITE4_HERO_CTA_PRIMARY', 'Create Your Profile'),
            'hero_cta_secondary' => env('SITE4_HERO_CTA_SECONDARY', 'Browse Profiles'),
            'show_hero_stats' => env('SITE4_SHOW_HERO_STATS', true),
            'why_title' => env('SITE4_WHY_TITLE', 'Thoughtful connections for every generation'),
            'why_text' => env('SITE4_WHY_TEXT', 'Support your family\'s search with a platform designed for meaningful, culturally aligned introductions and long-term compatibility.'),
            'community_title' => env('SITE4_COMMUNITY_TITLE', 'Matches rooted in Dev Bhoomi values'),
            'community_subtitle' => env('SITE4_COMMUNITY_SUBTITLE', 'Discover profiles suited to tradition, lifestyle, education and family expectations within the Dev Bhoomi community.'),
            'primary_color' => env('SITE4_PRIMARY_COLOR', '#0d6b6a'),
            'secondary_color' => env('SITE4_SECONDARY_COLOR', '#1a2433'),
            'accent_color' => env('SITE4_ACCENT_COLOR', '#d7a963'),
            'support_email' => env('SITE4_SUPPORT_EMAIL', 'info@devbhoomirishtey.com'),
            'support_phone' => env('SITE4_SUPPORT_PHONE'),
            'support_address' => env('SITE4_SUPPORT_ADDRESS'),
            'social' => [
                'facebook' => env('SITE4_SOCIAL_FACEBOOK'),
                'x' => env('SITE4_SOCIAL_X'),
                'instagram' => env('SITE4_SOCIAL_INSTAGRAM'),
                'youtube' => env('SITE4_SOCIAL_YOUTUBE'),
            ],
            'android_app_url' => env('SITE4_ANDROID_APP_URL'),
            'ios_app_url' => env('SITE4_IOS_APP_URL'),
        ],
    ],

    'current' => null,
];
